name: Daily Currency ETL

on:
  schedule:
    - cron: '0 6 * * *'   # Runs daily at 6:00 AM UTC (adjust for your timezone)
  workflow_dispatch:        # Allow manual triggering via GitHub UI

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run ETL Pipeline
      env:
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_NAME: ${{ secrets.DB_NAME }}
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        python run_pipeline.py

